version: "3.5"

services:

  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    container_name: "catalog_api"
    image: task6/catalogserivce
    restart: "no"
    ports:
      - "8090:8000"
    env_file:
      - ".env"
    depends_on:
      - db

  app_grpc:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    image: task6/catalogserivce
    container_name: "catalog_grpc"
    command: "./start_grpc.sh"
    restart: "no"
    ports:
      - "50051:50051"
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    image: mysql:8
    volumes:
      - ./db/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3396:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
